# Generated by Django 5.1.5 on 2025-04-26 11:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.CharField(max_length=250, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
