# Generated by Django 5.1.5 on 2025-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_alter_movie_desc_alter_movie_img_alter_movie_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='caption',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
