# Generated by Django 5.1.5 on 2025-06-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
